services:

  node:
    image: node
    command: /bin/sh -c "while sleep 1000; do :; done"
    networks:
      - servers
    volumes:
      - ./:/app
    ports:
      - 3001:3000
    working_dir: /app


  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
    ports:
      - '${FORWARD_MONGO_PORT:-27017}:27017'
    networks:
      - servers

  mongo-express:
    image: mongo-express
    ports:
      - ${FORWARD_MONGO_EXPRESS_PORT:-8081}:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASS}
      ME_CONFIG_MONGODB_URL: mongodb://${DB_USER}:${DB_PASS}@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    networks:
      - servers

networks:
  servers:
    driver: bridge
